coverage:
  # acceptable: current >= 60% && diff >= 0.5%
  badge:
    path: docs/coverage.svg
  paths:
    - docs/coverage.out
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  # acceptable: 1min30sec
  badge:
    path: docs/time.svg
diff:
  datastores:
    - artifact://rizalgowandy/library-template-go
push:
  if: is_default_branch
comment:
  if: is_pull_request
  deletePrevious: true
  hideFooterLink: true
report:
  if: is_default_branch
  datastores:
    - artifact://rizalgowandy/library-template-go
