package entity

type AutoGenerated struct {
	ErrorCode string `json:"error_code"`
	HTTPCode  string `json:"http_code"`
	Limit     int    `json:"limit"`
	NodeCount int    `json:"node_count"`
	Nodes     []any  `json:"nodes"`
	Page      int    `json:"page"`
	PageCount int    `json:"page_count"`
	Success   bool   `json:"success"`
}
