name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod' # The Go version to download (if necessary) and use.

      - name: Check Go Version
        run: go version

      - name: Get Vendor
        run: go mod vendor -v

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install Go Test Summary
        run:  go install gotest.tools/gotestsum@latest

      - name: Run Build
        run: task build

      - name: Run Unit Tests
        run: task unit_tests
